version: "3.8"
services:
  redis:
      image: redis:7
  backend:
    build:
      context: ./Backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/coworkify
      - REDIS_HOST=redis
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
  frontend:
    build:
      context: ./Frontend/Cowork-app
    ports:
      - "5173:80"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: